### ISSUE TITLE
When retriving data from api, )]} appear before json object. 

### ISSUE THREAD

**Issue by ronashdkl** [luyadev/luya-kickstarter#29]
![image](https://user-images.githubusercontent.com/14940889/42929942-4534a5a6-8b5b-11e8-862d-6af198287c1c.png)

![image](https://user-images.githubusercontent.com/14940889/42930003-7a523af0-8b5b-11e8-8a79-f9e23bfb551e.png)

**Comment by nadar** [comment]
This is an except behavior in order to prevent json hijacking => https://github.com/luyadev/luya-module-admin/issues/93

If you want to access to LUYA Apis you can check for `X-CRUFT-LENGTH` header and remove the part from the string (https://github.com/luyadev/luya/blob/master/core/web/filters/JsonCruftFilter.php).

Or simply use the https://github.com/luyadev/luya-headless which is taking care of this.

**Comment by nadar** [comment]
You can also turn of the json cruft for all apis in the admin: https://github.com/luyadev/luya-module-admin/blob/master/src/Module.php#L100

**Comment by ronashdkl** [comment]
ah i see, i didn't notice that. Thank you.
